### ISSUE TITLE
hook suggestion: check-jsonschema

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/precommend#11]
https://check-jsonschema.readthedocs.io/en/latest/precommit_usage.html

e.g.

```
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-actions
      - id: check-readthedocs
      - id: check-dependabot
```
