### ISSUE TITLE
duplicate / misplaced comments

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/precommend#9]
- duplicate end-of-file-fixer
- comments misplaced
```
repos:
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
      # Run Black - the uncompromising Python code formatter
  - id: black-jupyter

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
      # Ensure existence of newline characters at file ends
  - id: end-of-file-fixer
      # Make sure that contained YAML files are well-formed
  - id: check-yaml
      # Trim trailing whitespace of all sorts
  - id: trailing-whitespace
      # Apply a file size limit of 500kB
  - id: check-added-large-files
      # Simple parser validation of e.g. pyproject.toml
  - id: check-toml
      # Unify file endings
  - id: end-of-file-fixer
      # Sort lines in requirements files
  - id: mixed-line-ending

- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
      # GitHub Actions Workflow linter
  - id: actionlint

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
      # Make sure that Jupyter notebooks under version control
      # have their outputs stripped before committing
  - id: nbstripout
    files: .ipynb

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.5.0
  hooks:
      # Automatically format/sanitize setup.cfg
  - id: setup-cfg-fmt

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
      # Validate the contents of pyproject.toml
  - id: validate-pyproject

```
